= Good Enough Architecture
:imagesdir: ./images

== 本リポジトリについて
本リポジトリは、弊社(link:https://www.genba-oriented.com[合同会社 現場指向^])が「十分に良い(Good Enough)」と考える、アプリケーションのアーキテクチャとそのサンプルプログラムを公開したものです。フリーマーケットを題材にしたサンプルプログラム（フリマアプリという名前）を実装しています。

公開しているプログラムやドキュメントは https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0^] ライセンスですので、自由にご利用いただいて構いません。本リポジトリをベースにして、個別の開発プロジェクトで適宜カスタマイズして利用することを想定しています。ただし、ご利用によって何かしらの不都合が生じた場合は自己責任となることをご了承ねがいます。また、内容は時間とともに変更していく予定です。

もし、プログラムにおかしなところがありましたら、Issueでご連絡いただけると大変ありがたいです。


== コンセプト

アプリケーションを開発する際の設計思想や技術には、さまざまなものが存在します。新規の開発プロジェクトでは、高度な設計思想や最新の技術を採用したくなるものです。

しかし、高度な設計思想や最新の技術を採用すれば、プロジェクトが円滑に進むという訳ではありません。逆に学習コストがあがったり、ブラックボックスな部分が多くなって、問題が起きたときにハマるリスクがあります。

本リポジトリのアーキテクチャは、できるだけ分かりやすく、ハマりにくいアーキテクチャをコンセプトに作成しています。

== システム構成
SPAとAPIサーバで構成するオーソドックスな構成です。認証はOpenID Connectを使用します。

image::system.drawio.svg[]

|===
|構成物|説明

|SPA|JavaScriptで作成されたSPA(Single Page Application)です。
|IdP|OpenID Connectに対応したIdentity Providerです。サンプルプログラムではKeycloakという製品を使用しています。
|Webサーバ兼BFF|SPAのプログラムを静的ファイルとして配信するWebサーバと、APIサーバにリクエストを受け流すBFF(Backend For Frontend)です。BFFは、OpenID Connectの役割で言うところのClientに該当し、IdPから取得したトークンを管理します。
|APIサーバ|APIサーバです。SPAから呼び出してもらうREST APIを提供します。
|RDB|リレーショナルデータベースです。
|===


== SPA周りの特徴

=== SSRを使用しないピュアなSPA
昨今のフロントエンド開発では、Next.jsやNuxtといった、Server Side Rendering(SSR)に対応したフレームワークが人気です。しかし、ハイドレーションなど、裏で行われる処理がブラックボックスになってしまい、問題が起きたときにハマるリスクがあります。

本リポジトリは、SSRを一切行わず、UIコンポーネントの処理はすべてブラウザ上で行います。これにより、問題が起きたときの切り分けがしやすくなります。

=== SPAを配信するWebサーバがBFFを兼務

APIサーバへのReverse Proxyの機能や、OpenID Connectの認証の機能を持つBFFを、SPAのJavaScirptプログラムを配信するするWebサーバで動かします。WebサーバはNode.jsで実行します。これにより以下の利点があります。

* ローカルでSPAを開発する際のNode.jsのサーバ(dev serverと呼ばれたりします)で動かすことができるため、開発時に別途BFFのプロセスを立ち上げる手間がない
* デプロイして動かす際、BFFのサーバインスタンスが不要

=== セッションデータを保持するストレージが不要

BFF上で管理する、トークンなどを含むセッションデータは、Cookieに含めています。これにより、セッションデータを保持するためのストレージが不要です。

== APIサーバの特徴
=== トランザクションスクリプトパターンを採用したオーソドックスな業務ロジック
昨今の業務ロジックの実装の方法論として、ドメインモデルパターンに属するドメイン駆動設計が人気です。しかし、学習コストが高くなったり、初学者にとって難解なソースコードになるリスクがあります。

本リポジトリは、業務ロジックの一連の処理を手続き的に記載する、いわゆるトランザクションスクリプトパターンを採用しています。これにより、ソースコードが取っつきやすく分かりやすくなります。 トランザクションスクリプトパターンのデメリットである、1メソッドの処理が長くなったり冗長な記述が多くなりがちなことについては、サービス層のプログラムを積極的に分割することで対応するスタンスです。

=== Domaを使用した軽量なデータアクセス
昨今のデータアクセスの実装の手段として、Spring Data JPAが人気です。Spring Data JPAを使用すると、開発者のコードが劇的に少なくなります。しかし、内部の処理がブラックボックスになったり、JPA自体の学習コストが高くなるリスクもあります。

本リポジトリでは、日本産のライブラリである https://github.com/domaframework/doma[Doma^]を使用しています。Domaは、2Way-SQL footnote:[プログラムが読み込むテンプレートとしても使えるし、開発者がpsqlのようなツールで実行することもできるSQL] が有名ですが、本リポジトリは2Way-SQLの機能は使用せずCriteria APIと呼ばれる機能を使っています。Criteria APIは、JPAのCriteria APIと似ており、Entityクラスからメタモデルを生成してタイプセーフにSQLを記述できます。また、セレクトしたレコードをEntityオブジェクトに変換してくれます。ただ、JPAのようにEntityのライフサイクルの管理や、キャッシュの制御は行いません。JPAから難易度が高い機能を削ぎ落とした軽量なORマッパーのイメージです。


== フォルダ構成

|===
|フォルダ名|説明

|api|APIサーバのソースコード
|spa-bff|SPAおよびBFFのソースコード
|keycloak|動作確認用のKeycloak
|requirements|サンプルプログラムの要件定義
|===


== 実行方法
実行方法の詳細は、各フォルダ内の README.adoc をご参照ください。
以下の順番で実行していきます。

1. Keycloakを起動(keyclakフォルダ)
1. APIサーバを起動(apiフォルダ)
1. SPA・BFFを起動(spa-bffフォルダ)




