logging:
    level:
        org:
            springframework:
                web: debug
                security: trace
spring:
    datasource:
        password: fleamarket
        url: jdbc:postgresql://localhost:5432/fleamarket
        username: fleamarket
    security:
        oauth2:
            resourceserver:
                jwt:
                  issuer-uri: http://localhost:18080/realms/master
                  audiences: gea-api
